version: '3'

services:

  web:
    build:
      context: ./docker
    container_name: web
    ports:
      - "8081:80"
    links:
      - db
    volumes:
      - ./app:/var/www/html/
    environment:
      DB_DATABASE: database
      DB_HOST : db
      DB_USER: admin
      DB_PASSWORD: pass
    networks:
      - php-network


  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    networks:
      - php-network


  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8082:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - php-network

networks:
  php-network:
    driver: bridge

volumes:
  db_data: